### ISSUE TITLE
Add installation docs to readme

### ISSUE THREAD

**Issue by paulirish** [cliffrowley/homebrew-chromium#1]
i use homebrew a lot but don't think i've installed from a custom formula like this.  

can you add the one-liner?

Also if it said "homebrew depot_tools formula" somewhere, that'd be awesome for SEO. :)

**Comment by cliffrowley** [comment]
Hey there, sorry I'm so terrible at replying to my messages!  This package was never really intended for public consumption, it was just something I was toying with - hence I (intentionally) left it a little vague.

FYI you can install any custom formula just by specifying the raw url instead if the package name.  For example:

`brew install https://raw.githubusercontent.com/cliffrowley/homebrew-chromium/master/depot.rb`

:-)

**Comment by cliffrowley** [comment]
I won't fix (unfortunately) this because it won't be maintained going forward..  Sorry about that ;-)
